version: 1

environment:
  grid_dimensions:
    width: 10
    height: 10
  obstacles_coordinates:
    - [2, 2]
    - [3, 3]
    - [4, 4]
    - [5, 5]
    - [6, 6]
    - [7, 7]
    - [8, 8]
  episode_time_limit: 10

agent:
  start_coordinates: [0, 0]
  goal_coordinates: [9, 9]
  velocity: 1
  visibility_radius: 5

seekers:
  - start_coordinates: [0, 9]
    velocity: 1
  - start_coordinates: [9, 0]
    velocity: 1
